-- Japanese COA General Purpose 
-- First Choice Internet Ltd., B.Plagge, 05 Oct. 2007
-- 2008-07-05: bplagge - added Chinese simplified account translations
-- 2009-11-12: bplagge - use language codes ja_JP and zh_CN
-- 2010-01-25: bplagge - setup costs corrected as expenses, some additional expense accounts
-- Just delete any accounts not needed after importing the scheme, beats entering all manually (or add -- at the beginning)
-- Account groups (first number in accountnumber defines to which group it belongs)
-- 1 : Fixed Assets, Capital, Accruals and long term loans
-- 2 : Current Assets
-- 3 : Current Liabilities
-- 35 : Long Term Liabilities
-- 4 : Share Capital
-- 5 : Administrative Expenses
-- 7 : Other Profit & Loss
-- 9 : P&L Calculation
-- 19 : Stocks (minerals, parts not yet assembled etc)
-- 5 : Costs Accounts
-- 5 : Accounts to recharge several Direct Costs to separate departments
-- 6 : Assembly Costs
-- 7 : Stocks (Trade Articles, half-finished assemblies, projects under construction)
-- 8 : Accounts for deciding Sales Result
-- 9 : Accounts for deciding Profit & Loss (P/L)
-- COA
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1000','Fixed Asset & Capital','H','A','','1000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1010','Land','A','A','','1010','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1020','Accumulated Amortization Land','A','A','','1020','1');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1100','Buildings','A','A','','1100','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1110','Accumulated Amortization Buildings','A','A','','1110','1');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1120','Associated Equipment','A','A','','1120','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1130','Accumulated Depreciation Associated Equipment','A','A','','1130','1');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1140','Vehicles','A','A','','1140','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1150','Accumulated Depreciation Vehicles','A','A','','1150','1');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1160','Equipment/Machines','A','A','','1160','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1170','Depreciation Equipment/Machines','A','A','','1170','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1180','Tools','A','A','','1180','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1190','Accumulated Depreciation Tools','A','A','','1190','1');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1300','Licenses and other Assets','H','A','','1300','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1310','Telephone License (NTT)','A','A','','1310','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1320','License to use Facilities','A','A','','1320','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1330','Industrial Prod. Licenses','A','A','','1330','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1340','Sales Licenses','A','A','','1340','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1350','Leases Granted','A','A','','1350','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1360','Securities','A','A','','1360','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1370','Fixed Deposit Account','A','A','','1370','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1380','Fixed Periodical Deposits','A','A','','1380','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1400','Guarantee Money Paid','A','A','','1200','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1900','Inventory Assets','H','A','','1900','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1910','Inventory Sales Products','A','A','IC','1910','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1920','Inventory Raw Materials','A','A','IC','1920','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1930','Inventory Supplies','A','A','IC','1930','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1940','Finished Goods Inventory','A','A','IC','1940','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1950','Trade Products','A','A','IC','1950','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1960','By-Products','A','A','IC','1960','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2000','Current Assets','H','A','','2000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2010','Ordinary Bank Account','A','A','AR_paid:AP_paid','2010','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2020','Current Account','A','A','AR_paid:AP_paid','2020','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2030','Cash','A','A','AR_paid:AP_paid','2030','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2040','Petty Cash','A','A','AR_paid:AP_paid','2040','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2050','Savings Account (Notice)','A','A','','2050','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2100','Receivables & Settlement','H','A','','2100','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2110','Accounts Receivable','A','A','AR','2110','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2120','Notes Receivable','A','A','AR','2120','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2130','Uncollected Income','A','A','','2130','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2140','Doubtful Debts','A','A','','2140','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2160','Short Term Loan Receivable','A','A','','2160','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2170','Advance Payments','A','A','','2170','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2180','Advances for Expenses','A','A','','2180','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2190','Temporary Advances','A','A','','2190','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3000','Current Liabilities','H','A','','3000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3010','Accounts Payable','A','L','AP','3010','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3020','Note Payments','A','A','AP','3020','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3030','Accrued Revenue Receivable','A','L','AP','3030','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3040','Dishonored Notes','A','A','','3040','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3050','Wages Payable','A','L','AP','3050','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3060','Expenses Payable','A','A','','3060','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3070','Company Tax Payable','A','A','','3070','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3080','Enterprise Tax Payable','A','A','','3080','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3090','Interest Payable','A','L','','3090','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3100','Software','A','A','','3100','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3110','Dividends Payable','A','A','','3110','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3120','Executive Bonus Payable','A','A','','3120','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3130','Emoluments Payable','A','A','','3130','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3140','Outstanding Shareholders Payment','A','A','','3140','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3150','Employee Taxes Retained','A','A','IC_expense','3150','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3160','Deferred Tax Liability','A','A','','3160','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3170','Short Term Debts','A','L','','3170','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3180','Experiment & Research Costs','A','L','','3180','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3190','Temporary Receipts','A','L','','3190','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3200','Note Receivable Discounted','A','L','','3200','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3210','Note Endorsements','A','L','','3210','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3220','Advance Payments Received','A','L','','3220','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3240','Consumption Tax (PO) 5%)','A','A','AP_tax:IC_taxpart:IC_taxservice','3240','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3250','Withholding Tax (5%)','A','L','AP_tax:IC_taxservice','3250','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3260','Consumption Tax','A','L','AR_tax:IC_taxpart:IC_taxservice','3260','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3500','Long Term Liabilities','H','A','','3500','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3510','Guarantee Money Received','A','A','','3510','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3520','Revenue Received in Advance','A','L','','3520','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3530','Long Term Debts','A','L','','3530','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3540','Real Estate Mortgage Loan','A','L','','3540','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3550','Long Term Accrued Amount Payable','A','L','','3550','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3560','Reserve for Retirement Allowance','A','L','','3560','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4000','Share Capital','H','Q','','4000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4010','Companys Capital','A','Q','','4010','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4020','Shares on Hand','A','Q','','4020','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4030','Share Valuation Variances','A','Q','','4030','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4100','Reserves and Provisions','H','Q','','4100','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4110','Reserves for Bad Debts','A','Q','','4110','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4120','Special Deposit Account','A','Q','','4120','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4130','Special Reserves/Funds','A','Q','','4130','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4140','Loss Provision','A','Q','','4140','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4150','Maintenance Provision','A','Q','','4150','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4160','Legal Capital Surplus','A','Q','','4160','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4170','A/R Provision','A','Q','','4170','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4180','Warranty Provision','A','Q','','4180','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4200','Long Term Loans/Deposits','H','Q','','4200','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4210','Long Term Loan Granted','A','Q','','4210','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4220','Long Term Fixed Deposit','A','Q','','4220','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4230','Long Term Loan Granted','A','Q','','4230','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4240','Long Term Fixed Deposit','A','Q','','4240','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4300','Profits','H','Q','','4300','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4310','This Years Profit After Charges','A','Q','','4310','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4320','Undistributed Profits','A','Q','','4320','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4400','Intermediate Accounts','H','L','','4440','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4410','Intermediate Calcuation Starting Balance','A','A','','4410','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4500','Payroll Expenses','H','L','','4500','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4510','Salaries','A','E','','4510','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4520','Officers Remuneration','A','E','','4520','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4530','Bonus','A','E','','4530','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4540','Legal Welfare Expenses','A','E','','4540','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4550','Welfare Expenses','A','E','','4550','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4560','Retirement Allowances','A','E','','4560','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4570','Subcontract Expenses','A','E','','4570','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4580','Staff Training Expenses','A','E','','4580','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4590','Other Wages','A','E','','4590','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4600','Emoluments','A','E','','4600','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4700','Profit on Ordinary Business','H','I','','4700','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4710','Regular Sales','A','I','AR_amount:IC_sale','4710','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4720','Sales of Services','A','I','AR_amount:IC_income','4720','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4730','Sales Reductions','A','E','','4730','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4740','PO Discounts Received',' ','I','','4740','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4800','Cost of Goods Sold','H','I','','4800','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4810','Surcharge Indirect Sales Costs',' ','E','','4810','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4820','COGS Regular Sales','A','E','AP_amount:IC_cogs','4820','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4830','Goods Purchased','A','E','AP_amount:IC_expense:IC_cogs','4830','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4840','Additional PO costs','A','E','','4840','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5000','Depreciation','H','E','','5000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5010','Depreciation Buildings','A','E','','5010','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5020','Depreciation Equipment/Machines','A','E','','5020','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5050','Depreciation Vehicles','A','E','','5050','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5060','Depreciation Computers','A','E','','5060','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5070','Depreciation of Old Expenses','A','E','','5070','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5080','Depreciation of Expenses','A','E','','5080','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5090','Inventory Write-Off','A','E','','5090','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5100','Bad Claims Write-Off','A','E','','5100','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5200','Licenses, rent, lease','H','E','5200','5200','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5210','Licenses & Software','A','E','','5210','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5220','Rent Paid','A','E','','5220','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5230','Lease Costs','A','E','','5230','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5300','R&D Expenses','H','E','','5300','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5310','R&D Expenses','A','E','','5310','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5350','Vehicle Expenses','H','E','','5350','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5360','Vehicle Expenses','A','E','','5360','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5400','Insurance Costs','H','E','','5400','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5410','Insurance Costs','A','E','','5410','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5450','Maintenance Costs','H','E','','5450','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5460','Repair Expenses','A','E','','5460','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5500','Taxes and Duties','H','E','','5500','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5510','Company Tax','A','E','','5520','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5520','Adjustment of Company Tax','A','E','','5520','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5530','Tax and Duties','A','E','','5530','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5550','Legal Setup Costs','H','E','','5550','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5560','Founding Expenses','A','E','','5560','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5570','Business Start-Up Expenses','A','E','','5570','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5600','Administration Costs','H','E','','5600','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5610','Heat, Light, Water Expenses','A','E','IC_expense','5610','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5620','Travel & Commuting Expenses','A','E','IC_expense','5620','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5630','Information Systems','A','E','IC_expense','5630','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5640','Office Goods','A','E','IC_expense','5640','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5650','Communication Expenses','A','E','IC_expense','5650','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5660','Newspapers','A','E','IC_expense','5660','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5670','Meeting Expenses','A','E','IC_expense','5670','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5680','Entertainment Expenses','A','E','IC_expense','5680','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5690','Advertising Expenses','A','E','AP_amount:IC_expense','5690','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5700','Transport Expenses','A','E','','5700','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5710','Membership Fees','A','E','IC_expense','5710','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5720','Banking Fees','A','E','AP_amount:IC_expense','5720','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5730','Donations','A','E','IC_expense','5730','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5740','Accounting Fees','A','E','IC_expense','5740','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5750','General Administration','A','E','IC_expense','5750','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES  ('5760','Consumables','A','E','AP_amount:IC_expense','5760','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5770','Other Services','A','E','AP_amount:IC_expense','5770','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5780','Intercompany Charges','A','E','AP_amount:IC_expense','5780','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5790','Other Expenses','A','E','','5790','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5800','Adjustments','H','E','','5800','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5810','Cash Discrepancies','A','E','','5810','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5820','Inventory Discrepancies','A','E','','5820','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5830','Special costs & Benefits','A','E','','5830','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7000','Other Profit/Loss','H','I','','7000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7010','Interest Received','A','I','','7010','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7020','Interest Paid','A','E','','7020','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7030','Foreign Currency Profit','A','I','','7030','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7040','Foreign Currency Loss','A','E','','7040','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7050','Gain on Sales of Securities','A','I','','7050','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7060','Losses on Sales of Securities','A','E','','7060','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7070','Gain from Sales of Fixed Assets','A','I','','7070','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7080','Loss from Sales of Fixed Assets','A','E','','7080','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7090','Other Losses','A','E','','7090','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7100','Other Revenues','A','I','','7100','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7110','Bad Debt Losses','A','E','','7110','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7120','Dividends Received (gross)','A','I','','7120','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7130','Dividend Charges Withhold','A','E','','7130','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7999','Carried Forward Depreciation of Assets','A','E','','7999','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9000','P&L Calculation','H','I','','9000','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9810','Profit & Loss Carried Forward','A','E','','9810','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9850','Reduction of Reserves','A','E','','9850','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9860','Mid-Term Dividends','A','E','','9860','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9870','Transfer to Legal Reserves','A','E','','9870','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9900','Shareholders Dividends','A','E','','9900','0');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('9999','Current Undistributed Profit/Loss (Transfer)','A','I','','9999','0');

-- account translations Japanese
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1000'),'ja_JP','資産の部');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1010'),'ja_JP','土地 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1020'),'ja_JP','蓄積土地の償却');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '10329'),'ja_JP','資本金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1100'),'ja_JP','建物');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1110'),'ja_JP','蓄積建物の償却');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1120'),'ja_JP','附属設備');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1130'),'ja_JP','蓄積附属設備 の償却');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1140'),'ja_JP','車両運搬具');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1150'),'ja_JP','蓄積減価償却車両運搬具');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1160'),'ja_JP','機械装置');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1170'),'ja_JP','減価償却機械装置');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1180'),'ja_JP','工具器具備品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1190'),'ja_JP','減価償却工具器具備品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1300'),'ja_JP','許可と他の資産');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1310'),'ja_JP','電話加入権');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1320'),'ja_JP','施設利用権');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1330'),'ja_JP','工業所有権');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1340'),'ja_JP','営業権');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1350'),'ja_JP','借地権');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1360'),'ja_JP','有価証券');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1370'),'ja_JP','定期預金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1380'),'ja_JP','定期積金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1400'),'ja_JP','差入保証金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1900'),'ja_JP','在庫資産');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1910'),'ja_JP','商品在庫');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1920'),'ja_JP','原材料在庫');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1930'),'ja_JP','貯蔵品在庫');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1940'),'ja_JP','製品在庫');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1950'),'ja_JP','商品棚卸高');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1960'),'ja_JP','副産物作業くず在庫');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2000'),'ja_JP','流動資産計');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2010'),'ja_JP','普通預金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2020'),'ja_JP','当座預金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2030'),'ja_JP','現金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2040'),'ja_JP','小口現金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2050'),'ja_JP','通知預金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2100'),'ja_JP','売掛金と決済');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2110'),'ja_JP','売掛金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2120'),'ja_JP','受取手形');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2120'),'ja_JP','貸し倒れ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2130'),'ja_JP','未収収益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2160'),'ja_JP','短期貸付金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2170'),'ja_JP','立替金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2180'),'ja_JP','前払費用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2190'),'ja_JP','仮払金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3000'),'ja_JP','流動負債計');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3010'),'ja_JP','買掛金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3020'),'ja_JP','支払手形');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3030'),'ja_JP','未収入金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3040'),'ja_JP','不渡手形');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3050'),'ja_JP','退職給与繰入額');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3060'),'ja_JP','未払費用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3070'),'ja_JP','未払法人税等');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3080'),'ja_JP','未払事業税等');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3090'),'ja_JP','未払い利息 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3100'),'ja_JP','ソフトウェア');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3110'),'ja_JP','未払配当金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3120'),'ja_JP','未払役員賞与');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3130'),'ja_JP','未払役員の手当');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3140'),'ja_JP','未払い株主決済');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3150'),'ja_JP','預り金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3160'),'ja_JP','繰延税金負債');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3170'),'ja_JP','短期借入金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3180'),'ja_JP','試験研究費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3190'),'ja_JP','仮受金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3200'),'ja_JP','割引手形');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3210'),'ja_JP','裏書手形');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3220'),'ja_JP','前受金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3240'),'ja_JP','払消費税');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3250'),'ja_JP','源泉徴収税5% ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3260'),'ja_JP','受消費税(5%)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3500'),'ja_JP','固定負債計');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3510'),'ja_JP','預り保証金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3520'),'ja_JP','前受収益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3530'),'ja_JP','長期借入金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3540'),'ja_JP','不動産抵当貸付');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3550'),'ja_JP','長期未払金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3560'),'ja_JP','退職給与引当金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4010'),'ja_JP','資本金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4020'),'ja_JP','自己株式');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4030'),'ja_JP','株式評価差額金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4100'),'ja_JP','引当金 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4110'),'ja_JP','貸倒引当金(投)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4120'),'ja_JP','別段預金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4130'),'ja_JP','別途積立金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4140'),'ja_JP','損失引当金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4150'),'ja_JP','維持引当金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4160'),'ja_JP','資本準備金 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4170'),'ja_JP','賃倒引当金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4180'),'ja_JP','製品保証引当金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4200'),'ja_JP','長期性預金 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4210'),'ja_JP','長期貸付金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4240'),'ja_JP','長期固定性預金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4300'),'ja_JP','利益(損害)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4310'),'ja_JP','当期末経費控除後利益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4320'),'ja_JP','未処理利益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4400'),'ja_JP','中級勘定 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4410'),'ja_JP','期首残高の中級計算');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4500'),'ja_JP','給与費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4510'),'ja_JP','給料手当');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4520'),'ja_JP','役員報酬');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4530'),'ja_JP','賞与');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4540'),'ja_JP','法定福利費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4550'),'ja_JP','福利厚生費 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4560'),'ja_JP','退職金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4570'),'ja_JP','外注費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4580'),'ja_JP','採用教育費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4590'),'ja_JP','雑給');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4600'),'ja_JP','役員の手当 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4700'),'ja_JP','営業損益の部');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4710'),'ja_JP','売上高');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4720'),'ja_JP','役務収益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4730'),'ja_JP','売上値引高 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4740'),'ja_JP','仕入値引高');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4800'),'ja_JP','売上原価');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4810'),'ja_JP','追加間接販売減価');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4820'),'ja_JP','販売減価 販売');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4830'),'ja_JP','仕入高');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4840'),'ja_JP','追加仕入費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5000'),'ja_JP','一般管理費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5010'),'ja_JP','減価償却建物');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5020'),'ja_JP','減価償却機械装置');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5050'),'ja_JP','減価償却車両運搬具');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5060'),'ja_JP','減価コンピュータ費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5070'),'ja_JP','長前費用償却');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5080'),'ja_JP','減価償却費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5090'),'ja_JP','在庫棚卸高 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5100'),'ja_JP','貸倒損失(販)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5200'),'ja_JP','権利、家賃、リース');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5210'),'ja_JP','実施料とソフト');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5220'),'ja_JP','地代家賃');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5230'),'ja_JP','リース料');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5300'),'ja_JP','研究開発費 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5310'),'ja_JP','研究開発費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5350'),'ja_JP','車両費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5360'),'ja_JP','車両費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5400'),'ja_JP','保険料 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5410'),'ja_JP','保険料');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5450'),'ja_JP','維持費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5460'),'ja_JP','修繕費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5500'),'ja_JP','税額');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5510'),'ja_JP','法人税等');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5520'),'ja_JP','法人税等調整額');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5530'),'ja_JP','租税公課');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5550'),'ja_JP','法定準備金計');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5560'),'ja_JP','創立費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5570'),'ja_JP','開業費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5600'),'ja_JP','管理費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5610'),'ja_JP','水道光熱費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5620'),'ja_JP','旅費交通費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5630'),'ja_JP','情報システム');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5640'),'ja_JP','事務用品費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5650'),'ja_JP','通信費 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5660'),'ja_JP','新聞図書費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5670'),'ja_JP','会議費 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5680'),'ja_JP','交際費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5690'),'ja_JP','広告宣伝費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5700'),'ja_JP','荷造運賃発送費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5710'),'ja_JP','会費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5720'),'ja_JP','支払手数料 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5730'),'ja_JP','寄付金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5740'),'ja_JP','諸会費 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5750'),'ja_JP','一般管理費 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5760'),'ja_JP','消耗品 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5770'),'ja_JP','その他サービス');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5780'),'ja_JP','会社間経費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5790'),'ja_JP','雑費');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5810'),'ja_JP','現金違');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5820'),'ja_JP','在庫違');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5830'),'ja_JP','特別費用 & 利益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7000'),'ja_JP','営業外収益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7010'),'ja_JP','受取利息');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7020'),'ja_JP','支払利息');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7030'),'ja_JP','外通貨利益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7040'),'ja_JP','外通貨損害 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7050'),'ja_JP','有価証券売却益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7060'),'ja_JP','有価証券売却損');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7070'),'ja_JP','固定資産売却益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7080'),'ja_JP','固定資産売却損');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7090'),'ja_JP','雑損失');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7100'),'ja_JP','雑収入');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7110'),'ja_JP','貸倒損失(営)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7120'),'ja_JP','受配当金(総)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7130'),'ja_JP','受配当金費の預り金 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7999'),'ja_JP','繰延資産償却 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9000'),'ja_JP','利益計算');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9850'),'ja_JP','中配当積立取崩');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9860'),'ja_JP','中間配当額');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9870'),'ja_JP','利益準備金積立');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9880'),'ja_JP','前期繰越損益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9900'),'ja_JP','末間配当額 ');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9999'),'ja_JP','当期未処分損益');

-- account translations simplified Chinese
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1000'),'zh_CN','固定资产');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1010'),'zh_CN','土地');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1020'),'zh_CN','累计推销土地');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1100'),'zh_CN','房屋及建筑');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1110'),'zh_CN','累计推销房屋');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1120'),'zh_CN','辅助设备');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1130'),'zh_CN','辅助设备折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1140'),'zh_CN','机动车辆');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1150'),'zh_CN','累积折旧车辆');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1160'),'zh_CN','机(器)具及设备');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1170'),'zh_CN','折旧机(器)具及设备');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1180'),'zh_CN','工具');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1190'),'zh_CN','累积折旧工具');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1300'),'zh_CN','执照和其他资产');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1310'),'zh_CN','电话使用许可证');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1320'),'zh_CN','设备/设施许可证');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1330'),'zh_CN','工业生产许可证');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1340'),'zh_CN','销售许可证');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1350'),'zh_CN','租赁许可');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1360'),'zh_CN','证券');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1370'),'zh_CN','固定存款帐户');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1380'),'zh_CN','固定定期存款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1400'),'zh_CN','已付保证金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1900'),'zh_CN','存量资产');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1910'),'zh_CN','待销产品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1920'),'zh_CN','原料存货');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1930'),'zh_CN','辅助材料存货');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1940'),'zh_CN','成品存货');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1950'),'zh_CN','贸易产品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '1960'),'zh_CN','副产品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2000'),'zh_CN','流动资产');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2010'),'zh_CN','普通银行户头');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2020'),'zh_CN','现银行户头');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2030'),'zh_CN','现金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2040'),'zh_CN','零用金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2050'),'zh_CN','储蓄存款帐户(通知)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2100'),'zh_CN','已收与支付');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2110'),'zh_CN','应收帐款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2120'),'zh_CN','应收票据');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2130'),'zh_CN','未收所得');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2140'),'zh_CN','可疑债务');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2160'),'zh_CN','应收短期贷款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2170'),'zh_CN','预付款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2180'),'zh_CN','预支费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '2190'),'zh_CN','临时预支');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3000'),'zh_CN','流动负债');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3010'),'zh_CN','应付帐款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3020'),'zh_CN','已付票据');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3030'),'zh_CN','应收收入');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3040'),'zh_CN','拒付票据');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3050'),'zh_CN','应付工资');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3060'),'zh_CN','应付支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3070'),'zh_CN','应付公司所得税');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3080'),'zh_CN','应付企业税');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3090'),'zh_CN','应付利息');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3100'),'zh_CN','软件');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3110'),'zh_CN','应付股利');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3120'),'zh_CN','应付行政津贴');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3130'),'zh_CN','应付薪水');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3140'),'zh_CN','未清股东应付帐');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3150'),'zh_CN','员工税剩余');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3160'),'zh_CN','递延所得税负债');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3170'),'zh_CN','短期债务');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3180'),'zh_CN','实验与研究支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3190'),'zh_CN','暫收款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3200'),'zh_CN','应收票据贴现');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3210'),'zh_CN','票据背书');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3220'),'zh_CN','已收预付款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3240'),'zh_CN','购买增值税(5%)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3250'),'zh_CN','预扣所得税(5%)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3260'),'zh_CN','销售增值税(5%)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3500'),'zh_CN','长期借款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3510'),'zh_CN','已收保证金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3520'),'zh_CN','预收收入');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3530'),'zh_CN','长期债务');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3540'),'zh_CN','不动产抵押贷款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3550'),'zh_CN','长期应付款额');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '3560'),'zh_CN','退休金准备');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4000'),'zh_CN','股本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4010'),'zh_CN','公司资本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4020'),'zh_CN','持有股票');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4030'),'zh_CN','股票市值变化');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4100'),'zh_CN','储备金和准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4110'),'zh_CN','不良债券准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4120'),'zh_CN','特种存款帐户');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4130'),'zh_CN','特别储备基金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4140'),'zh_CN','损失准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4150'),'zh_CN','维护准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4160'),'zh_CN','法律资本剩余');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4170'),'zh_CN','应收帐款准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4180'),'zh_CN','担保准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4200'),'zh_CN','长期贷款/存款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4210'),'zh_CN','已付长期贷款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4240'),'zh_CN','长期定期存款');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4300'),'zh_CN','盈余');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4310'),'zh_CN','今年利润');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4320'),'zh_CN','未分配利润');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4400'),'zh_CN','期内帐单');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4410'),'zh_CN','期内计算期初余额');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4500'),'zh_CN','薪金支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4510'),'zh_CN','工资');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4520'),'zh_CN','办公人员薪酬');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4530'),'zh_CN','红利');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4540'),'zh_CN','法律福利支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4550'),'zh_CN','福利支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4560'),'zh_CN','退休津贴');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4570'),'zh_CN','转包支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4580'),'zh_CN','员工培训支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4590'),'zh_CN','其他工资');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4600'),'zh_CN','津贴');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4700'),'zh_CN','普通业务利润');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4710'),'zh_CN','定期销售');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4720'),'zh_CN','服务销售');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4730'),'zh_CN','销售折扣');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4740'),'zh_CN','已收购买折扣');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4800'),'zh_CN','销货成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4810'),'zh_CN','间接销售成本附加费');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4820'),'zh_CN','常规销售产品成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4830'),'zh_CN','货物购入');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '4840'),'zh_CN','附加购买成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5000'),'zh_CN','折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5010'),'zh_CN','房屋折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5020'),'zh_CN','折旧机(器)具及设备');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5050'),'zh_CN','机动车辆折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5060'),'zh_CN','计算机折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5070'),'zh_CN','老支出折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5080'),'zh_CN','支出折旧');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5090'),'zh_CN','存货转销');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5100'),'zh_CN','不良债权转销');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5200'),'zh_CN','执照,租金,租赁');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5210'),'zh_CN','执照与软件');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5220'),'zh_CN','已付租金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5230'),'zh_CN','租赁成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5300'),'zh_CN','研究与开发支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5310'),'zh_CN','研究与开发支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5350'),'zh_CN','机动车辆费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5360'),'zh_CN','机动车辆费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5400'),'zh_CN','保险成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5410'),'zh_CN','保险成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5450'),'zh_CN','维护成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5460'),'zh_CN','维修支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5500'),'zh_CN','税与关税');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5510'),'zh_CN','公司税');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5520'),'zh_CN','调整');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5530'),'zh_CN','税与关税');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5550'),'zh_CN','法律设置成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5560'),'zh_CN','创设费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5570'),'zh_CN','开办费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5600'),'zh_CN','管理成本');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5610'),'zh_CN','供热,照明,水费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5620'),'zh_CN','差旅费');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5630'),'zh_CN','信息系统'); 
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5640'),'zh_CN','办公用品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5650'),'zh_CN','通讯支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5660'),'zh_CN','报纸杂志费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5670'),'zh_CN','会议支出');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5680'),'zh_CN','娱乐费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5690'),'zh_CN','广告费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5700'),'zh_CN','交通费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5710'),'zh_CN','会员费');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5720'),'zh_CN','银行费');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5730'),'zh_CN','赞助费');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5740'),'zh_CN','会计费');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5630'),'zh_CN','消耗品');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5790'),'zh_CN','其他费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5810'),'zh_CN','现金差异');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5820'),'zh_CN','存货差异');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '5830'),'zh_CN','特别成本与收益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7000'),'zh_CN','其他盈亏');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7010'),'zh_CN','已收利息');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7020'),'zh_CN','已付利息');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7030'),'zh_CN','外汇盈利');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7040'),'zh_CN','外汇亏损');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7050'),'zh_CN','证券销售增益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7060'),'zh_CN','证券销售亏损');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7070'),'zh_CN','固定资产销售增益');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7080'),'zh_CN','固定资产销售亏损');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7090'),'zh_CN','其他亏损');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7100'),'zh_CN','其他收入');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7110'),'zh_CN','坏帐损失');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7120'),'zh_CN','已收股利(毛利)');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7130'),'zh_CN','预扣股利费用');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '7999'),'zh_CN','资产折旧推后');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9000'),'zh_CN','盈亏计算');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9810'),'zh_CN','盈亏推后');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9850'),'zh_CN','储备削减');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9860'),'zh_CN','中期股利');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9870'),'zh_CN','转入法定准备金');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9900'),'zh_CN','股东股利');
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from chart where accno = '9999'),'zh_CN','现未分配盈亏(转)');

-- consumption tax
INSERT INTO tax (chart_id,rate,taxnumber,validto) VALUES ((select id from chart where accno = '3240'),'0.05','',NULL);
INSERT INTO tax (chart_id,rate,taxnumber,validto) VALUES ((select id from chart where accno = '3250'),'-0.1','',NULL);
INSERT INTO tax (chart_id,rate,taxnumber,validto) VALUES ((select id from chart where accno = '3260'),'0.05','',NULL);

-- language
INSERT INTO language (code,description) VALUES ('ja_JP','Japan/Japanese');
INSERT INTO language (code,description) VALUES ('en','English');
INSERT INTO language (code,description) VALUES ('zh_CN','China/Chinese (Simplified)');
-- currency precision
INSERT INTO curr (rn,curr,precision) VALUES ('1','JPY','0');
INSERT INTO curr (rn,curr,precision) VALUES ('2','EUR','2');
INSERT INTO curr (rn,curr,precision) VALUES ('3','USD','2');
INSERT INTO curr (rn,curr,precision) VALUES ('4','CNY','2');
INSERT INTO curr (rn,curr,precision) VALUES ('5','KRW','2');
INSERT INTO curr (rn,curr,precision) VALUES ('6','NT$','2');
-- business types
INSERT INTO business (description,discount) VALUES ('卸販売 (Wholesale)','0');
INSERT INTO business (description,discount) VALUES ('小売設備 (Retail)','0');
-- defaults
-- INSERT INTO defaults (fldname,fldvalue) VALUES ('version','2.8.8');
INSERT INTO defaults (fldname,fldvalue) VALUES ('inventory_accno_id','10100');
INSERT INTO defaults (fldname,fldvalue) VALUES ('income_accno_id','10193');
INSERT INTO defaults (fldname,fldvalue) VALUES ('expense_accno_id','10072');
INSERT INTO defaults (fldname,fldvalue) VALUES ('fxgain_accno_id','10212');
INSERT INTO defaults (fldname,fldvalue) VALUES ('fxloss_accno_id','10279');
INSERT INTO defaults (fldname,fldvalue) VALUES ('glnumber','L-00000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('sinumber','SI-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('vinumber','VI-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('batchnumber','B-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('vouchernumber','V-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('sonumber','SO-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('ponumber','PO-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('sqnumber','SQ-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('rfqnumber','SR-<%date%>-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('partnumber','<%partsgroup 1%>-0000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('employeenumber','000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('customernumber','000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('vendornumber','000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('projectnumber','P-000000');
INSERT INTO defaults (fldname,fldvalue) VALUES ('precision','0');
INSERT INTO defaults (fldname,fldvalue) VALUES ('weightunit','kg');
-- partsgroup
INSERT INTO partsgroup (partsgroup,pos) VALUES ('Services','0');
-- translations
INSERT INTO translation (trans_id,language_code,description) VALUES ((select id from partsgroup where partsgroup = 'Services'),'ja_JP','サービス');
-- standard parts
INSERT INTO parts (partnumber,description,priceupdate,inventory_accno_id,income_accno_id,expense_accno_id,partsgroup_id) VALUES ('S-0001','Banking Fee','2010-01-01',NULL,(select id from chart where accno = '4710'),(select id from chart where accno = '5720'),(select id from partsgroup where partsgroup = 'Services'));
