When you have some time please go over the files and add the missing
translations.

The translation mechanism changed from previous versions
and you can finetune translations on a module by module basies if
you remove the 'all' file. Once the 'all' file is removed all
the translations are taken from the individual files. Missing
translations are now kept in a {module}.missing file.

If you require any assistance let me know.

-- 
kind regards,
Dieter Simader, SQL-Ledger
http://www.sql-ledger.org

